// --- UPDATE THESE TWO VARIABLES ---
const REPO_OWNER = "BSatya-Saketh"; 
const REPO_NAME = "Leetcode_Solutions";        
// ----------------------------------

// 🚀 UPGRADED: Bulletproof Base64 Encoding
function utf8ToBase64(str) {
    return btoa(unescape(encodeURIComponent(str)));
}

// 🚀 UPGRADED: Bulletproof Upload (Bypasses Chrome Cache!)
async function uploadFileToGitHub(token, path, content, commitMessage) {
    const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`;
    const encodedContent = utf8ToBase64(content);
    let sha = null;

    // Step 1: Get SHA (with cache busting so Chrome doesn't lie to us)
    try {
        const getResponse = await fetch(url, {
            headers: { 'Authorization': `Bearer ${token}`, 'Accept': 'application/vnd.github.v3+json' },
            cache: 'no-store' // <--- THE MAGIC CACHE BUSTER
        });
        if (getResponse.ok) {
            const fileData = await getResponse.json();
            sha = fileData.sha;
        }
    } catch (e) {}

    // Step 2: Push the file
    try {
        const body = { message: commitMessage, content: encodedContent };
        if (sha) body.sha = sha;

        const response = await fetch(url, {
            method: 'PUT',
            headers: {
                'Authorization': `Bearer ${token}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(body)
        });

        if (response.ok) {
            console.log(`LeetSync: Successfully pushed -> ${path}`);
            return true;
        } else {
            const errorResult = await response.json();
            console.error(`LeetSync: Failed to push ${path}. Reason: ${errorResult.message}`);
            return false;
        }
    } catch (error) {
        console.error("LeetSync: Network error during upload", error);
        return false;
    }
}

// 📊 NEW: Dynamic Branch Fetcher
async function getDefaultBranch(token) {
    const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}`;
    try {
        const response = await fetch(url, {
            headers: { 'Authorization': `Bearer ${token}` },
            cache: 'no-store'
        });
        const data = await response.json();
        return data.default_branch || "main";
    } catch (e) {
        return "main";
    }
}

// 📊 UPGRADED: Master README Generator
async function generateMasterReadme(token, platform, language) {
    // Wait 2 seconds to give GitHub servers time to index the newly uploaded problem
    await new Promise(resolve => setTimeout(resolve, 2000));

    const branch = await getDefaultBranch(token);
    const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/git/trees/${branch}?recursive=1`;
    
    try {
        const response = await fetch(url, {
            headers: { 'Authorization': `Bearer ${token}`, 'Accept': 'application/vnd.github.v3+json' },
            cache: 'no-store' // <--- THE MAGIC CACHE BUSTER
        });
        
        if (!response.ok) return;
        const data = await response.json();

        let easy = 0, medium = 0, hard = 0;
        
        data.tree.forEach(item => {
            // Only count READMEs deeper in the tree, ignoring the Master README itself
            if (item.path.startsWith(`${platform}/${language}/`) && item.path.endsWith('README.md') && item.path.split('/').length > 3) {
                if (item.path.includes('/Easy/')) easy++;
                if (item.path.includes('/Medium/')) medium++;
                if (item.path.includes('/Hard/')) hard++;
            }
        });

        const total = easy + medium + hard;

        const masterContent = `# ☕ ${language} Problem Solving Portfolio\n\n` +
                              `Welcome to my ${language} solutions for **${platform}**. This repository is automatically synced using LeetSync.\n\n` +
                              `### 📊 Live Stats\n` +
                              `![Total](https://img.shields.io/badge/Total_Solved-${total}-blue) ` +
                              `![Easy](https://img.shields.io/badge/Easy-${easy}-brightgreen) ` +
                              `![Medium](https://img.shields.io/badge/Medium-${medium}-orange) ` +
                              `![Hard](https://img.shields.io/badge/Hard-${hard}-red)\n\n` +
                              `---\n*Auto-generated by LeetSync*`;

        const masterPath = `${platform}/${language}/README.md`;
        await uploadFileToGitHub(token, masterPath, masterContent, `Update ${platform} ${language} Master Dashboard`);
        
    } catch (error) {
        console.error("LeetSync: Failed to generate Master README", error);
    }
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "SUBMISSION_ACCEPTED") {
        const data = message.payload;
        console.log(`LeetSync Background: ${data.platform} Data received, preparing GitHub upload...`);

        chrome.storage.local.get(["githubToken", "syncCount"], async (result) => {
            const token = result.githubToken;
            let currentCount = result.syncCount || 0; 
            
            if (!token) {
                console.error("LeetSync: No GitHub token found!");
                return;
            }

            const folderName = data.title.replace(/[^a-zA-Z0-9 \-]/g, "").trim();
            const codePath = `${data.platform}/${data.languageFolder}/${data.difficulty}/${folderName}/Solution${data.fileExtension}`; 
            const readmePath = `${data.platform}/${data.languageFolder}/${data.difficulty}/${folderName}/README.md`;                   

            // 1. Upload the Source Code
            await uploadFileToGitHub(token, codePath, data.code, `Add ${data.difficulty} ${data.languageFolder} Solution from ${data.platform}`);
            
            // 2. Upload the Problem README
            let diffColor = "lightgrey";
            if (data.difficulty === "Easy") diffColor = "brightgreen";
            if (data.difficulty === "Medium") diffColor = "orange";
            if (data.difficulty === "Hard") diffColor = "red";

            const readmeContent = `# 📝 ${data.title} (${data.platform})\n\n` +
                                  `🔗 [Problem Link](${data.problemUrl})\n\n` +
                                  `![Difficulty](https://img.shields.io/badge/Difficulty-${data.difficulty}-${diffColor}) ` +
                                  `![Language](https://img.shields.io/badge/Language-${data.languageFolder}-blue)\n\n` +
                                  `### 💡 Tags\n${data.tags}\n\n` +
                                  `### 🚀 Performance\n- **Runtime:** ${data.runtime}\n- **Memory:** ${data.memory}\n\n` +
                                  `---\n\n` +
                                  `### 📜 Problem Description\n${data.description}`;
            
            await uploadFileToGitHub(token, readmePath, readmeContent, `Add README for ${data.title}`);

            // 3. Trigger the Master README Update!
            await generateMasterReadme(token, data.platform, data.languageFolder);

            currentCount++;
            chrome.storage.local.set({ syncCount: currentCount });
        });
    }
});