# -*- coding: utf-8 -*-
"""FL based IOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vQS1uzbMyHwtyjRBSdSDMEdmxaNPSfU
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import random
import math
import time
import json
import os
import matplotlib.pyplot as plt
from collections import deque
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif, VarianceThreshold
from sklearn.impute import SimpleImputer
import copy
import joblib
import gc




# Set random seeds for reproducibility
np.random.seed(42)
torch.manual_seed(42)
random.seed(42)

# Data Preprocessing Class
class preprocess_data():
    def __init__(self):
        self.file_path = None
        self.le = {}
        self.ss = {}
        self.feature_selecter = {}
        self.df = []
        self.num_cols = []
        self.cat_cols = []
        self.features = []
        self.target = ""
        self.clean_df = []
        self.X = []
        self.y = []
        self.X_train = []
        self.X_test = []
        self.y_train = []
        self.y_test = []

    def load_csv(self, file_path):
        self.file_path = file_path
        if not os.path.exists(self.file_path):
            raise FileNotFoundError(f"Dataset file '{self.file_path}' not found. Please ensure the file exists.")

        try:
            print(f"Loading dataset from {self.file_path}...")
            self.df = pd.read_csv(self.file_path)
            print(f"Dataset loaded successfully. Shape: {self.df.shape}")
        except Exception as e:
            raise Exception(f"Error loading dataset: {str(e)}")

    def handling_missing_values(self, file_path):

        self.load_csv(file_path)
        # Set features as all columns except last, target as last
        self.features = self.df.columns[:-1].tolist()
        self.target = self.df.columns[-1]

        # Identify numeric and categorical columns from features only
        self.num_cols = self.df[self.features].select_dtypes(include=np.number).columns.tolist()
        self.cat_cols = self.df[self.features].select_dtypes(include=['object']).columns.tolist()

        # Handle infinite values
        for col in self.df.columns:
            if pd.api.types.is_numeric_dtype(self.df[col]):
                mean_val = self.df[col][np.isfinite(self.df[col])].mean()
                self.df[col] = self.df[col].replace([np.inf, -np.inf], mean_val)

        # Handle missing numerical values
        for col in self.num_cols:
            if self.df[col].isnull().sum() > 0:
                imputer = SimpleImputer(strategy='mean')
                self.df[col] = imputer.fit_transform(self.df[col].values.reshape(-1, 1))

        # Handle missing categorical values
        for col in self.cat_cols:
            if self.df[col].isnull().sum() > 0:
                imputer = SimpleImputer(strategy='most_frequent')
                self.df[col] = imputer.fit_transform(self.df[col].values.reshape(-1, 1))

        return self.df, self.features, self.target

    def scaling_encoding(self):
        # Handle cardinality
        high_cardinality_cols = []
        low_cardinality_cols = []

        for col in self.cat_cols:
            unique_vals = self.df[col].nunique()
            if unique_vals > 10:
                high_cardinality_cols.append(col)
            else:
                low_cardinality_cols.append(col)

        # Label encode high cardinality
        for col in high_cardinality_cols:
            self.le[col] = LabelEncoder()
            self.df[col] = self.le[col].fit_transform(self.df[col].astype(str))

        # One-hot encode low cardinality
        self.df = pd.get_dummies(self.df, columns=low_cardinality_cols, drop_first=True)

        # Update feature list after encoding
        encoded_cols = list(self.df.columns)
        encoded_cols.remove(self.target)
        self.features = encoded_cols

        # Standard scaling
        for col in self.num_cols:
            self.ss[col] = StandardScaler()
            self.df[col] = self.ss[col].fit_transform(self.df[col].values.reshape(-1, 1))

        return self.df

    def handling_outliers(self):
        # Handle outliers using IQR
        def handle_outliers(df, col):
            Q1 = df[col].quantile(0.25)
            Q3 = df[col].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - 1.5 * IQR
            upper = Q3 + 1.5 * IQR
            df[col] = np.where(df[col] < lower, lower, df[col])
            df[col] = np.where(df[col] > upper, upper, df[col])
            return df

        for col in self.num_cols:
            self.df = handle_outliers(self.df, col)

        return self.df

    # def feature_selection(self):
    #     # Remove constant features

    #     vt = VarianceThreshold(threshold=0.0)
    #     X_vt = vt.fit_transform(self.df[self.features])
    #     self.features = [col for col, keep in zip(self.features, vt.get_support()) if keep]

    #     # Drop columns with NaNs
    #     self.df.dropna(axis=1, inplace=True)

    #     # Ensure selected features are still valid
    #     self.features = [f for f in self.features if f in self.df.columns]

    #     # Feature selection (k=10 or less)
    #     selector = SelectKBest(score_func=f_classif, k=min(10, len(self.features)))
    #     X_new = selector.fit_transform(self.df[self.features], self.df[self.target])
    #     mask = selector.get_support()
    #     selected_features = [feat for feat, keep in zip(self.features, mask) if keep]

    #     for col in selected_features:
    #         self.feature_selecter[col] = selector
    #     self.features = selected_features
    #     print(self.features)
    #     return self.features


    def train_split(self):
        # Prepare final cleaned DataFrame
        self.clean_df = self.df[self.features + [self.target]]

        # Final X and y (entire dataset, not split)
        self.X = self.df[self.features]
        self.y = self.df[self.target]

        print("Cleaned Data Shape: ", self.clean_df.shape)
        print("X Shape: ", self.X.shape)
        print("y Shape: ", self.y.shape)

        return self.clean_df, self.X, self.y

    def train_test_split(self):
        # Train-test split
        # Prepare final cleaned DataFrame
        self.clean_df = self.df[self.features + [self.target]]
        # Final X and y (entire dataset, not split)
        self.X = self.df[self.features]
        self.y = self.df[self.target]
        # Splitting the dataset
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(self.X, self.y, test_size=0.2, random_state=42)

        return self.clean_df, self.X_train, self.X_test, self.y_train, self.y_test

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1), :]

class MiniTransformerAutoencoder(nn.Module):
    def __init__(self, input_dim, latent_dim=32, n_heads=2, ff_dim=64, n_layers=2, seq_len=10):
        super(MiniTransformerAutoencoder, self).__init__()
        self.seq_len = seq_len
        self.input_dim = input_dim
        self.embedding = nn.Linear(input_dim, ff_dim)
        self.pos_encoder = PositionalEncoding(ff_dim, max_len=seq_len)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=ff_dim,
            nhead=n_heads,
            dim_feedforward=ff_dim,
            dropout=0.1,
            activation='relu',
            batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)

        self.encoder_fc = nn.Linear(ff_dim, latent_dim)
        self.decoder_fc = nn.Linear(latent_dim, ff_dim)
        self.output_layer = nn.Linear(ff_dim, input_dim)
    def get_weights(self):
      return {k: v.cpu().detach().clone() for k, v in self.state_dict().items()}

    def set_weights(self, weights):
      self.load_state_dict(weights)

    def forward(self, x):
        x = self.embedding(x)
        x = self.pos_encoder(x)
        x = self.transformer_encoder(x)
        latent = self.encoder_fc(x[:, -1, :])
        decoded = self.decoder_fc(latent).unsqueeze(1).repeat(1, self.seq_len, 1)
        output = self.output_layer(decoded)
        return output, latent

# Base class for all nodes in the IoT architecture
class Node:
    def __init__(self, node_id, name):
        self.node_id = node_id
        self.node_name = name
        self.parent = None
        self.children = []
        self.data_buffer = []
        self.last_update_time = time.time()

    def add_child(self, child):
        self.children.append(child)
        child.parent = self

    def send_data(self, data, destination):
        print(f"\n[{self.node_name}] Sending data to {destination.node_name}")
        destination.receive_data(data, self)

    def receive_data(self, data, source):
        print(f"\n[{self.node_name}] Received data from {source.node_name}\n")
        self.data_buffer.append(data)
        self.last_update_time = time.time()

    def process_data(self):
        raise NotImplementedError("Subclasses must implement process_data()")

class Edge(Node):
  def __init__(self, node_id, name, local_df):
    super().__init__(node_id, name)
    self.df = local_df
    self.X = self.df.drop(columns=["Label"]).values
    self.y = self.df["Label"].values

    self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    self.sequence_length = 10
    self.epochs = 1
    self.local_model = None
    self.global_model_weights = None
    self.local_model_weights = None

  def recieve_global_model(self, global_model_weights):
    print(f"[{self.node_name}] Received global model from Gateway.")
    self.global_model_weights = global_model_weights

  def process_data(self):

    input_dim = self.X.shape[1]

    if self.global_model_weights:
        self.local_model = MiniTransformerAutoencoder(
            input_dim=input_dim,
            latent_dim=32,
            ff_dim=64,
            n_heads=2,
            n_layers=2,
            seq_len=self.sequence_length
        ).to(self.device)
        self.local_model.set_weights(self.global_model_weights) # Loading global model
        print(f"\n[Sensor {self.node_id}] Loaded global model for fine-tuning.")
    else:
        self.local_model = MiniTransformerAutoencoder(
            input_dim=input_dim,
            latent_dim=32,
            ff_dim=64,
            n_heads=2,
            n_layers=2,
            seq_len=self.sequence_length
        ).to(self.device)
        print(f"[Sensor {self.node_id}] Training from scratch.") # Training local model

    print(f"Sensor: {self.node_id} started training!\n")

    # Filter only benign samples
    benign_indices = self.y == 0  # assuming 0 = benign, 1 = attack
    benign_X = self.X[benign_indices]

    # Generate sequences only from benign data
    X_seq = self.create_sequences(benign_X, self.sequence_length)
    X_tensor = torch.tensor(X_seq, dtype=torch.float32).to(self.device)

    # Training starts
    self.train_local_model(X_tensor, self.epochs)

  def create_sequences(self, data, seq_len):
    sequences = []
    for i in range(len(data) - seq_len):
        seq = data[i:i+seq_len]
        sequences.append(seq)
    return np.array(sequences)

  def train_local_model(self, X_tensor, epochs=5):
    self.local_model.train()
    optimizer = torch.optim.Adam(self.local_model.parameters(), lr=0.001)
    criterion = nn.MSELoss()

    for epoch in range(epochs):
        output, _ = self.local_model(X_tensor)
        loss = criterion(output, X_tensor)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 1 == 0:
            print(f"[Sensor {self.node_id}] Epoch {epoch+1}/{epochs} | Loss: {loss.item():.4f}")
    print(f"[Sensor {self.node_id}] Final Local Loss: {loss.item():.4f}")


    self.local_model_weights = self.local_model.get_weights()

  def send_model_weights(self):
    if self.parent:
        packet = {
            'node_id': self.node_id,
            'weights': self.local_model_weights
        }
        self.send_data(packet, self.parent)


class Gateway(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.received_weights = []
        self.global_model_weights = None

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if 'weights' in data:
            self.received_weights.append(data['weights'])

    def process_data(self):
        if self.parent:
            self.send_data(self.received_weights, self.parent)

    def receive_global_model(self, global_weights):
      self.global_model_weights = global_weights
      print(f"[{self.node_name}] Received global model from Fog.")
      for edge in self.children:
        edge.recieve_global_model(global_weights)



class Fog(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.global_model_weights = None

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if isinstance(data, list):
            self.received_weights = data
        elif isinstance(data, dict) and 'weights' in data:
            self.received_weights = [data['weights']]
        else:
            self.received_weights = []

    def aggregate_weights(self, weights_list):
        avg_weights = copy.deepcopy(weights_list[0])
        for k in avg_weights:
            for i in range(1, len(weights_list)):
                avg_weights[k] += weights_list[i][k]
            avg_weights[k] /= len(weights_list)
        return avg_weights

    def process_data(self):
        if not hasattr(self, 'received_weights') or not self.received_weights:
            print(f"[{self.node_name}] No weights to aggregate.")
            return

        self.global_model_weights = self.aggregate_weights(self.received_weights)
        print(f"Global model aggregated. Now sent to Edge nodes.\n")

        for gateway in self.children:
          if hasattr(gateway, "receive_global_model"):
              gateway.receive_global_model(self.global_model_weights)

    def recieve_global_model(self, global_model_weights):
        self.global_model = global_model_weights
        for gateway in self.children:
          if hasattr(gateway, "receive_global_model"):
              gateway.receive_global_model(self.global_model_weights)

    def send_global_weights(self):
        if self.parent:
            packet = {
                'node_id': self.node_id,
                'weights': self.global_model_weights
            }
            self.send_data(packet, self.parent)

class Proxy(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.received_weights = []
        self.global_model_weights = None

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if 'weights' in data:
            self.received_weights.append(data['weights'])

    def process_data(self):
        if self.parent:
            self.send_data(self.received_weights, self.parent)

    def receive_global_model(self, global_weights):
      self.global_model_weights = global_weights
      print(f"[{self.node_name}] Received global model from Fog.")
      for fog in self.children:
        print(f"[{fog.node_name}] Received global model from Gateway.")
        fog.recieve_global_model(global_weights)

class Cloud(Node):
  def __init__(self, node_id, name):
      super().__init__(node_id, name)
      self.global_model_weights = None

  def receive_data(self, data, source):
      super().receive_data(data, source)
      if isinstance(data, list):
          self.received_weights = data
      elif isinstance(data, dict) and 'weights' in data:
          self.received_weights = [data['weights']]
      else:
          self.received_weights = []

  def aggregate_weights(self, weights_list):
      avg_weights = copy.deepcopy(weights_list[0])
      for k in avg_weights:
          for i in range(1, len(weights_list)):
              avg_weights[k] += weights_list[i][k]
          avg_weights[k] /= len(weights_list)
      return avg_weights

  def process_data(self):
      if not hasattr(self, 'received_weights') or not self.received_weights:
          print(f"[{self.node_name}] No weights to aggregate.")
          return

      self.global_model_weights = self.aggregate_weights(self.received_weights)
      print(f"Global model aggregated. Now sent to Fog nodes.\n")

      for proxy in self.children:
        if hasattr(proxy, "receive_global_model"):
            proxy.receive_global_model(self.global_model_weights)

class IOTSimulation:
    def __init__(self, file_path):
        self.file_path = file_path
        # Load data only once
        self.dp = preprocess_data()
        self.df, self.features, self.target = self.dp.handling_missing_values("CIC-IDS-2017.csv")
        self.df = self.dp.scaling_encoding()
        self.df = self.dp.handling_outliers()
        self.clean_df, self.X, self.y = self.dp.train_split()

        # Encode labels
        self.y = np.array([0 if str(label).strip().upper() == "BENIGN" else 1 for label in self.y])
        self.clean_df["Label"] = self.y

                # Split into 8 parts for 8 edge nodes
        self.split_dfs = np.array_split(self.clean_df, 2)

        # Creating nodes
        self.edge_nodes = [
            Edge(i + 1, f"Sensor {i+1}", self.split_dfs[i].copy()) for i in range(2)
        ]

        self.gateway_nodes = [
            Gateway(1,"Bridge 1")
        ]

        self.fog_nodes = [
            Fog(1, "Fog Layer 1")
        ]

        self.proxy_nodes = [
            Proxy(1,"Proxy Layer 1")
        ]

        self.cloud_nodes = [
            Cloud(1,"Cloud Layer 1")
        ]

        # Connecting the layers
        for i in range(2):
            self.gateway_nodes[0].add_child(self.edge_nodes[i])

        self.fog_nodes[0].add_child(self.gateway_nodes[0])

        self.proxy_nodes[0].add_child(self.fog_nodes[0])

        self.cloud_nodes[0].add_child(self.proxy_nodes[0])

        self.count = 0

    def run(self):
        gc.collect()
        torch.cuda.empty_cache()
        print("\n========== Federated Round START ==========")

        # edge_threads = []

        # for edge in self.edge_nodes:
        #     thread = Thread(target=edge.process_data)
        #     edge_threads.append(thread)
        #     thread.start()

        # # Wait for all edge nodes to finish training + sending weights
        # for thread in edge_threads:
        #     thread.join()

        self.count+=1
        if self.count != 2:
          self.run_one()
          self.run_two()
        else:
          self.run_two()
          self.run_one()

        print("========== Federated Round END ==========\n")

    def run_one(self):
        # Step 1: Edge training + latent vector sending
        for edge in self.edge_nodes:
            edge.process_data()
            edge.send_model_weights()

        # Step 2: Gateways forward data to Fog
        for gateway in self.gateway_nodes:
            gateway.process_data()  # Send collected vectors to Fog

        # Step 3: Fog processes latent vectors and trains Transformer
        for fog_node in self.fog_nodes:
            fog_node.process_data()

    def run_two(self):
        for fog in self.fog_nodes:
            fog.send_global_weights()

        for proxy in self.proxy_nodes:
            proxy.process_data()

        for cloud in self.cloud_nodes:
            cloud.process_data()

if __name__ == "__main__":
    sim = IOTSimulation("/content/CIC-IDS-2017.csv")
    for round in range(2):
        print(f"\n----- ROUND {round+1} -----")
        sim.run()